"""Add game statistics fields to waitlist_signups

Revision ID: 1a3f9729c395
Revises: 13efaaefd519
Create Date: 2025-11-20 10:37:13.273039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a3f9729c395'
down_revision: Union[str, Sequence[str], None] = '13efaaefd519'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waitlist_signups', sa.Column('game_played', sa.Boolean(), nullable=True))
    op.add_column('waitlist_signups', sa.Column('final_bankroll', sa.Float(), nullable=True))
    op.add_column('waitlist_signups', sa.Column('total_bets', sa.Integer(), nullable=True))
    op.add_column('waitlist_signups', sa.Column('win_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('waitlist_signups', 'win_rate')
    op.drop_column('waitlist_signups', 'total_bets')
    op.drop_column('waitlist_signups', 'final_bankroll')
    op.drop_column('waitlist_signups', 'game_played')
    # ### end Alembic commands ###
